import {UserLdap} from "./user-ldap";

export const LDAP_USERS: UserLdap[] = [
  {
    id:1,
    login: "test.v1",
    nom: "V1",
    prenom: "Test",
    nomComplet: "V1 test",
    motDePasse: null,
    mail: "test.v1@epsi.fr",
    role: "ROLE_USER",
    employeNumero: 1,
    employeNiveau: 120,
    dateEmbauche: "2020-01-01",
    publisherId: 1,
    active: true,
  },
  {
    id:2,
    login: "test.v2",
    nom: "V2",
    prenom: "Test",
    nomComplet: "V2 test",
    motDePasse: null,
    mail: "test.v2@epsi.fr",
    role: "ROLE_USER",
    employeNumero: 2,
    employeNiveau: 220,
    dateEmbauche: "2020-02-02",
    publisherId: 2,
    active: true,
  },  {
    id:3,
    login: "test.v3",
    nom: "V3",
    prenom: "Test",
    nomComplet: "V3 test",
    motDePasse: null,
    mail: "test.v3@epsi.fr",
    role: "ROLE_USER",
    employeNumero: 3,
    employeNiveau: 220,
    dateEmbauche: "2020-02-02",
    publisherId: 3,
    active: true,
  },  {
    id:4,
    login: "test.v4",
    nom: "V4",
    prenom: "Test",
    nomComplet: "V4 test",
    motDePasse: null,
    mail: "test.v4@epsi.fr",
    role: "ROLE_USER",
    employeNumero: 4,
    employeNiveau: 220,
    dateEmbauche: "2020-02-02",
    publisherId: 4,
    active: true,
  },  {
    id:5,
    login: "test.v5",
    nom: "V5",
    prenom: "Test",
    nomComplet: "V5 test",
    motDePasse: null,
    mail: "test.v5@epsi.fr",
    role: "ROLE_USER",
    employeNumero: 5,
    employeNiveau: 220,
    dateEmbauche: "2020-02-02",
    publisherId: 5,
    active: true,
  },  {
    id:6,
    login: "test.v6",
    nom: "V6",
    prenom: "Test",
    nomComplet: "V6 test",
    motDePasse: null,
    mail: "test.v6@epsi.fr",
    role: "ROLE_USER",
    employeNumero: 6,
    employeNiveau: 220,
    dateEmbauche: "2020-02-02",
    publisherId: 6,
    active: true,
  },  {
    id:7,
    login: "test.v7",
    nom: "V7",
    prenom: "Test",
    nomComplet: "V7 test",
    motDePasse: null,
    mail: "test.v7@epsi.fr",
    role: "ROLE_USER",
    employeNumero: 7,
    employeNiveau: 220,
    dateEmbauche: "2020-02-02",
    publisherId: 7,
    active: true,
  },  {
    id:8,
    login: "test.v8",
    nom: "V8",
    prenom: "Test",
    nomComplet: "V8 test",
    motDePasse: null,
    mail: "test.v8@epsi.fr",
    role: "ROLE_USER",
    employeNumero: 8,
    employeNiveau: 220,
    dateEmbauche: "2020-02-02",
    publisherId: 8,
    active: true,
  },  {
    id:9,
    login: "test.v9",
    nom: "V9",
    prenom: "Test",
    nomComplet: "V9 test",
    motDePasse: null,
    mail: "test.v9@epsi.fr",
    role: "ROLE_USER",
    employeNumero: 9,
    employeNiveau: 220,
    dateEmbauche: "2020-02-02",
    publisherId: 9,
    active: true,
  },  {
    id:10,
    login: "test.v10",
    nom: "V10",
    prenom: "Test",
    nomComplet: "V10 test",
    motDePasse: null,
    mail: "test.v10@epsi.fr",
    role: "ROLE_USER",
    employeNumero: 10,
    employeNiveau: 220,
    dateEmbauche: "2020-02-02",
    publisherId: 10,
    active: true,
  },  {
    id:11,
    login: "test.v11",
    nom: "V11",
    prenom: "Test",
    nomComplet: "V11 test",
    motDePasse: null,
    mail: "test.v11@epsi.fr",
    role: "ROLE_USER",
    employeNumero: 11,
    employeNiveau: 220,
    dateEmbauche: "2020-02-02",
    publisherId: 11,
    active: true,
  },  {
    id:12,
    login: "test.v12",
    nom: "V12",
    prenom: "Test",
    nomComplet: "V12 test",
    motDePasse: null,
    mail: "test.v12@epsi.fr",
    role: "ROLE_USER",
    employeNumero: 12,
    employeNiveau: 220,
    dateEmbauche: "2020-02-02",
    publisherId: 12,
    active: true,
  },
];

